# Generated by Django 5.2.4 on 2025-07-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['id']},
        ),
    ]
