# Generated by Django 5.2.4 on 2025-08-02 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_material_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(
                choices=[
                    ('beginner', 'Начинающий'),
                    ('intermediate', 'Средний'),
                    ('advanced', 'Продвинутый'),
                ],
                default='beginner',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.JSONField(
                blank=True, default=list, help_text='Теги для рекомендаций'
            ),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'material',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='courses.material',
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='replies',
                        to='courses.comment',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'score',
                    models.FloatField(
                        help_text='Оценка релевантности курса для пользователя'
                    ),
                ),
                (
                    'reason',
                    models.TextField(blank=True, help_text='Причина рекомендации'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'course',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recommendations',
                        to='courses.course',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recommendations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'activity_type',
                    models.CharField(
                        choices=[
                            ('view', 'Просмотр'),
                            ('complete', 'Завершение'),
                            ('test_passed', 'Тест пройден'),
                            ('comment', 'Комментарий'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'score',
                    models.FloatField(
                        blank=True, help_text='Результат теста', null=True
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'course',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_activities',
                        to='courses.course',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='activities',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course', 'activity_type', 'created_at')},
            },
        ),
    ]
