# Generated by Django 5.2.4 on 2025-07-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['id']},
        ),
    ]
