# Generated by Django 5.2.4 on 2025-08-02 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_answer_options_alter_question_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='max_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(
                choices=[
                    ('multiple_choice', 'Множественный выбор'),
                    ('essay', 'Эссе'),
                    ('code', 'Код'),
                ],
                default='multiple_choice',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='CodeAnswer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code_text', models.TextField()),
                (
                    'ai_score',
                    models.FloatField(blank=True, help_text='Оценка AI', null=True),
                ),
                (
                    'human_score',
                    models.FloatField(
                        blank=True, help_text='Оценка преподавателя', null=True
                    ),
                ),
                (
                    'final_score',
                    models.FloatField(
                        blank=True, help_text='Итоговая оценка', null=True
                    ),
                ),
                (
                    'ai_feedback',
                    models.TextField(blank=True, help_text='Комментарий AI'),
                ),
                (
                    'test_results',
                    models.JSONField(
                        default=list, help_text='Результаты тестовых случаев'
                    ),
                ),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                (
                    'question',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='code_answers',
                        to='tests.question',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='code_answers',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeQuestion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'language',
                    models.CharField(
                        choices=[
                            ('python', 'Python'),
                            ('javascript', 'JavaScript'),
                            ('java', 'Java'),
                            ('cpp', 'C++'),
                        ],
                        default='python',
                        max_length=20,
                    ),
                ),
                (
                    'test_cases',
                    models.JSONField(
                        default=list, help_text='Тестовые случаи для проверки кода'
                    ),
                ),
                (
                    'ai_evaluation_enabled',
                    models.BooleanField(
                        default=True, help_text='Включить AI оценку кода'
                    ),
                ),
                (
                    'question',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='code_config',
                        to='tests.question',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EssayAnswer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('answer_text', models.TextField()),
                (
                    'ai_score',
                    models.FloatField(blank=True, help_text='Оценка AI', null=True),
                ),
                (
                    'human_score',
                    models.FloatField(
                        blank=True, help_text='Оценка преподавателя', null=True
                    ),
                ),
                (
                    'final_score',
                    models.FloatField(
                        blank=True, help_text='Итоговая оценка', null=True
                    ),
                ),
                (
                    'ai_feedback',
                    models.TextField(blank=True, help_text='Комментарий AI'),
                ),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                (
                    'question',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='essay_answers',
                        to='tests.question',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='essay_answers',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EssayQuestion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'keywords',
                    models.JSONField(
                        default=list,
                        help_text='Ключевые слова для автоматической оценки',
                    ),
                ),
                (
                    'min_length',
                    models.IntegerField(
                        default=50, help_text='Минимальная длина ответа'
                    ),
                ),
                (
                    'max_length',
                    models.IntegerField(
                        default=500, help_text='Максимальная длина ответа'
                    ),
                ),
                (
                    'ai_evaluation_enabled',
                    models.BooleanField(default=True, help_text='Включить AI оценку'),
                ),
                (
                    'question',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='essay_config',
                        to='tests.question',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
